name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:

  wheels_on_PR:
    if: ${{ github.event.pull_request.merged == true }}
    name: ${{ matrix.py }} ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [native]
        py: [cp310]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Show variables0
        run: echo '${{ toJSON(github) }}'    

      



  wheels:
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Show variables0
        run: echo '${{ toJSON(github) }}'

    

  sdist:
    name: source package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Show variables0
        run: echo '${{ toJSON(github) }}'

    

  upload_to_PyPI:
    name: Upload to PyPI
    needs: [wheels, sdist]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Show variables0
        run: echo '${{ toJSON(github) }}'

      - name: Show variables1
        run: echo 'RUN1'  


